# Generated by Django 3.0.5 on 2020-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['id'], 'verbose_name': 'AllPost', 'verbose_name_plural': 'AllPosts'},
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1),
        ),
    ]
